name = "contact-form-worker"
main = "worker.js"
compatibility_date = "2024-04-07"

[[d1_databases]]
binding = "DB"
database_name = "contacts"
database_id = "b00c3bea-2111-44bd-9016-1a99a5c55bf8"

[vars]
RESEND_API_KEY = "your_resend_api_key"
NOTIFY_EMAIL = "work.carvelruss@gmail.com"
